trigger:
  - master
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              npm ci
              npm run build
          - upload: dist
            artifact: dist
  - stage: Release
    condition: 'and(succeeded(), eq(variables[''Build.SourceBranch''], ''refs/heads/master''))'
    jobs:
      - job: Metadata
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: LoadJsonVariables@1
            inputs:
              JsonSource: ./package.json
              VariablePrefix: pkg
          - script: >-
              echo '##vso[task.setvariable
              variable=version;isOutput=true]$(pkg_version)'
            name: setVersion
      - deployment: GitHub_Release_Draft
        pool:
          vmImage: ubuntu-latest
        dependsOn: Metadata
        environment: github
        variables:
          version: '$[ dependencies.Metadata.outputs[''setVersion.version''] ]'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: dist
                - task: GitHubRelease@0
                  inputs:
                    gitHubConnection: decsys-pipelines
                    repositoryName: decsys/discrete-component
                    action: create
                    tagSource: manual
                    tag: $(version)
                    releaseNotesSource: input
                    releaseNotes: '`// TODO`'
                    isDraft: true
                    assets: $(Pipeline.Workspace)/dist/*.js
